[build]
  command = ""
  publish = "."
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"