#!/bin/bash

echo "🚀 Vivify Mountain - Quick Test Guide"
echo "======================================"
echo ""
echo "You can test the app directly from terminal WITHOUT VS Code!"
echo ""

# Check if we're in the right directory
if [ ! -d "backend" ] || [ ! -d "vivify-mountain" ]; then
    echo "❌ ERROR: Not in the vivify-wellness-platform directory"
    echo "Please navigate to your project folder first:"
    echo "  cd /path/to/your/vivify/project"
    exit 1
fi

echo "✅ Step 1: Install Dependencies"
echo "--------------------------------"
echo "Run these commands:"
echo ""
echo "# Backend:"
echo "cd backend"
echo "npm install"
echo ""
echo "# Vivify Mountain:"
echo "cd ../vivify-mountain"
echo "npm install"
echo ""
echo ""

echo "✅ Step 2: Set Up Environment Variables"
echo "---------------------------------------"
echo ""
echo "Backend (.env file in /backend/ folder):"
echo "----------------------------------------"
cat << 'EOF'
MONGODB_URI=mongodb://localhost:27017/vivify-mountain
PORT=3001
JWT_SECRET=your-secret-key-change-this
NODE_ENV=development
EOF
echo ""
echo ""

echo "Vivify Mountain (.env file in /vivify-mountain/ folder):"
echo "--------------------------------------------------------"
cat << 'EOF'
REACT_APP_API_URL=http://localhost:3001/api
EOF
echo ""
echo ""

echo "✅ Step 3: Start MongoDB"
echo "------------------------"
echo "Option A - Local MongoDB:"
echo "  mongod"
echo ""
echo "Option B - MongoDB Atlas (Cloud - FREE):"
echo "  1. Go to: https://www.mongodb.com/cloud/atlas/register"
echo "  2. Create free account"
echo "  3. Create a cluster"
echo "  4. Get connection string"
echo "  5. Use it in backend/.env as MONGODB_URI"
echo ""
echo ""

echo "✅ Step 4: Start the Backend"
echo "----------------------------"
echo "Terminal 1:"
echo "  cd backend"
echo "  npm start"
echo ""
echo "Should see: 🎮 Vivify Card Battle Server running on port 3001"
echo ""
echo ""

echo "✅ Step 5: Start Vivify Mountain"
echo "--------------------------------"
echo "Terminal 2:"
echo "  cd vivify-mountain"
echo "  npm start"
echo ""
echo "Should open browser to: http://localhost:3000"
echo ""
echo ""

echo "✅ Step 6: Test the Game!"
echo "-------------------------"
echo "1. Register a new account"
echo "2. Complete Training Grounds (build oxygen to 70% for 3 days)"
echo "3. Unlock Mt. Fuji"
echo "4. Start climbing!"
echo ""
echo ""

echo "🆘 Troubleshooting"
echo "------------------"
echo ""
echo "Backend won't start:"
echo "  • Check MongoDB is running"
echo "  • Check .env file exists in backend/"
echo "  • Check port 3001 is not in use: lsof -i :3001"
echo ""
echo "Frontend won't start:"
echo "  • Check .env file exists in vivify-mountain/"
echo "  • Check REACT_APP_API_URL is set correctly"
echo "  • Clear cache: rm -rf node_modules package-lock.json && npm install"
echo ""
echo "Can't connect to backend:"
echo "  • Verify backend is running on port 3001"
echo "  • Test: curl http://localhost:3001/api/health"
echo "  • Check .env in vivify-mountain has correct API URL"
echo ""
echo ""

echo "📝 Quick Commands Reference"
echo "---------------------------"
echo ""
echo "# Start backend:"
echo "cd backend && npm start"
echo ""
echo "# Start mountain game:"
echo "cd vivify-mountain && npm start"
echo ""
echo "# Test backend health:"
echo "curl http://localhost:3001/api/health"
echo ""
echo "# Check what's running on port 3001:"
echo "lsof -i :3001"
echo ""
echo "# Check what's running on port 3000:"
echo "lsof -i :3000"
echo ""
echo ""

echo "🎯 You're ready to test!"
echo "========================"
echo ""
echo "Next steps:"
echo "1. Make sure MongoDB is running"
echo "2. Open 2 terminals"
echo "3. Terminal 1: cd backend && npm start"
echo "4. Terminal 2: cd vivify-mountain && npm start"
echo "5. Browser should open to http://localhost:3000"
echo ""

